### ISSUE TITLE
Missing `link.js` file from the generator-cspell-dicts template

### ISSUE THREAD

**Issue by d2s** [Jason3S/cspell-dicts#10]
Noticed that the Yeoman generator is missing the `link.js` file.

It is not possible to link run `npm run cspell-link` without it.

```
➜  fonts git:(master) ✗ npm run cspell-link

> cspell-dict-fonts@1.0.0 cspell-link  [edited the full file system path out] /cspell-dicts/fonts
> node link.js

module.js:491
    throw err;
    ^

Error: Cannot find module ' [edited the full file system path out] /cspell-dicts/fonts/link.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cspell-dict-fonts@1.0.0 cspell-link: `node link.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cspell-dict-fonts@1.0.0 cspell-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Besides of that, apparently there should also be `unlink.js` and `util.js` so that the npm task would work properly. Copied such files manually from the recent `fr_FR` dictionary's directory to see whether things would work. Looks like that those files would either need to be added to the template, or alternatively the npm tasks could be updated to use some central tool instead of spreading similar files to each of the template directories.

**Comment by Jason3S** [comment]
You make a good point. They are copied from `util` just before publishing.  I'll fix that step.

**Comment by Jason3S** [comment]
Fixed. Please re-open if it is no.

**Comment by d2s** [comment]
Might want to add that step to the `README.md` too, so that people would know to run it?

```sh
npm run build
npm run prepublishOnly
npm run cspell-link
```

At least the `prepublishOnly` task is not automatically run when generating the new directory.

**Comment by Jason3S** [comment]
Good point.

I added a step in the generator to copy the util files. Most of the time, they only need to be copied once.

Given that change, do you think the `npm run prepublishOnly` is still necessary in the README?

**Comment by d2s** [comment]
Most likely not needed on the README, if that is now automatically run on the creation of a new dictionary directory.
