### ISSUE TITLE
Difference with Dicts in Jason3S/vscode-cspell-dict-extensions

### ISSUE THREAD

**Issue by jmfederico** [Jason3S/cspell-dicts#19]
Installing cspell in Visual Code I found two Spanish dictionaries. One that came with the Cspell [extension itself](https://github.com/Jason3S/cspell-dicts/tree/master/es_ES) and one that I [installed separetly](https://github.com/Jason3S/vscode-cspell-dict-extensions/tree/master/extensions/spanish).

Both are maintained by you, so I was wondering what differences they have, and why keep two separate Spanish dictionaries.

Thanks

**Comment by Jason3S** [comment]
Good question. I can see how it is not clear.

This dictionaries in this repository came first. `vscode-cspell-dict-extensions` came later to make it easier to install other dictionaries is VS Code.

The `vscode-cspell-dict-extensions` is only the extension to be installed in VS Code. It includes the Spanish dictionary from this repository. It is really just a simple wrapper for the language dictionaries that are not included by default.

If you use the extension, then you do not need to manually install the Spanish dictionary from this repository.

You will only need to install the dictionaries from this repository if you are using **cspell** as part of your build process.

**Comment by jmfederico** [comment]
Good, understood!

Thanks
