### ISSUE TITLE
Update Go dictionary for Go 1.10

### ISSUE THREAD

**Issue by AlekSi** [Jason3S/cspell-dicts#21]
Words are here: https://github.com/AlekSi/go-words/blob/master/go.txt

Not sure if https://github.com/Jason3S/cspell-dicts/tree/master/golang or https://github.com/Jason3S/cspell/tree/master/migrated_dictionaries should be updated. Probably one of them should be removed?

**Comment by Jason3S** [comment]
Thank you.

cspell-dicts in the place.

I'll remove the list from cspell/.../migrated_dictionaries

**Comment by Jason3S** [comment]
Thank you. I updated the dictionary.
