### ISSUE TITLE
Unable to publish cspell-dict-cs-cz

### ISSUE THREAD

**Issue by Jason3S** [Jason3S/cspell-dicts#25]
@Zereges 
Due to permission issue it is not currently possible to publish updates to cs_CZ dictionary.

[npm cspell-dict-cs-cz](https://www.npmjs.com/package/cspell-dict-cs-cz)

Please add: `jason-dent` to the list of maintainers:
[Package Access](https://www.npmjs.com/package/cspell-dict-cs-cz/access)

**Comment by Zereges** [comment]
@Jason3S 
Added you to list of maintainers. Sorry for inconvinience.

**Comment by Jason3S** [comment]
Thank you.
