### ISSUE TITLE
Problems with the danish dictionary

### ISSUE THREAD

**Issue by viktorstrate** [Jason3S/cspell-dicts#26]
2 days ago, I submitted a danish dictionary.
It seems like something have gone wrong when compressing `da_DK.trie.gz`
The file is only 20 bytes large, and when I uncompress the file, only an empty file comes out. [Link to file](https://github.com/Jason3S/cspell-dicts/blob/master/packages/da_DK/da_DK.trie.gz).

I have tried to compress the .dic file using cspell-tools, but this also generates a `.trie.gz` with the size of 20 bytes.
```bash
$ cspell-tools compile-trie da_DK.dic

Compile:
 output: default
 compress: true
 files:
  da_DK.dic


Process "da_DK.dic" to "da_DK.trie.gz"
Complete.
```

I have tried to load the .dic file uncompressed in my user settings:

```json
"cSpell.dictionaryDefinitions": [
        {
            "name": "danish",
            "path": "/Users/viktorstrate/Documents/dictionaries/da_DK.dic",
            "description": "Danish dictionary"
        }
    ],
```

But it doesn't look like it reconizes the affix file (.aff) located at "/Users/viktorstrate/Documents/dictionaries/da_DK.aff". Do I have to specify this path in my user settings, for cspell to use it?

Currently I use a 4,5mb wordlist, this works fine, but the CPU running at 100% when loading the word list.

```json
"cSpell.dictionaryDefinitions": [
        {
            "name": "danish-wordlist",
            "path": "/Users/viktorstrate/Documents/dictionaries/da_DK.txt",
            "description": "Danish (txt wordlist)"
        }
    ],
```

EDIT:
It looks like this is a problem with `hunspell-reader`, as it cannot convert the dic and aff files. Jason3S/hunspell-reader#2

**Comment by Jason3S** [comment]
I'll take a look this weekend.
