### ISSUE TITLE
Disable check on too long ALL CAPS words

### ISSUE THREAD

**Issue by rbalet** [Jason3S/cspell-dicts#57]
Because when Internationalizing an app we may use all caps words, it would be nice to disable the spell checker on an "all caps" words longer than 5 character.

![image](https://user-images.githubusercontent.com/44493964/54664938-e5825180-4ae5-11e9-80b8-990c2af70f3c.png)

**Comment by Jason3S** [comment]
This is a good question for [Issues · cspell](https://github.com/Jason3S/cspell/issues) or [Issues · vscode-spell-checker](https://github.com/Jason-Rev/vscode-spell-checker/issues)

You can add the following to VS Code settings:
``` JSON
    "cSpell.ignoreRegExpList": [
        "/[A-Z]{5,}/",
    ]
```

or to a `cspell.json` file in your workspace root:
``` JSON
    "ignoreRegExpList": [
        "/[A-Z]{5,}/",
    ]
```

**Comment by rbalet** [comment]
Make sense,
Thx for your answer, I close this issue :)
